// Isolated FastMX live-shadow process. The app is hard-locked to simulation in config.js as well as here.
module.exports = {
  apps: [{
    name: "poly-fastmx-simulation",
    script: "src/index.js",
    cwd: __dirname,
    exec_mode: "fork",
    instances: 1,
    autorestart: true,
    max_restarts: 50,
    restart_delay: 3000,
    max_memory_restart: "600M",
    time: true,
    merge_logs: true,
    out_file: "./data/fastmx-live/pm2-out.log",
    error_file: "./data/fastmx-live/pm2-err.log",
    env: {
      INSTANCE_NAME: "fastmx-live-simulation",
      MODE: "ui",
      AUTO_START: "1",
      EXECUTION_MODE: "simulation",
      SHADOW: "1",
      SHADOW_PARAMS_JSON: '{"STRATEGY":"helpme","SIZE":7,"H_START_S":0,"H_STOP_S":300,"H_CLOB_MID_VELOCITY_ON":true,"H_MID_VELOCITY_LOOKBACK_MS":3000,"H_MID_VELOCITY_MIN":0.02,"H_BINANCE_GAP_MOMENTUM_ON":true,"H_BINANCE_GAP_VELOCITY_LOOKBACK_MS":3000,"H_BINANCE_GAP_VELOCITY_MIN":5,"H_BINANCE_TREND_ON":true,"H_BINANCE_TREND_LOOKBACK_SEC":30,"H_BINANCE_TREND_MIN_PCT":0.05,"H_BINANCE_COUNTERTREND_LOOKBACK_SEC":60,"H_BINANCE_COUNTERTREND_MIN_PCT":0.075,"H_BINANCE_GAP_AGREE_ON":false,"H_HEDGE_ON":true,"H_HEDGE_RETAIN_SH":1,"H_REVERSAL_ON":true,"H_REVERSAL_RESIDUAL_SH":4,"H_REVERSAL_CONFIRM_MS":1000,"H_OPPOSITE_CANDIDATE_RESET_MS":3000,"H_REVERSAL_MIN_PAIR_EDGE":-0.1,"H_REVERSAL_MAX_WORST_LOSS_USD":10,"H_REVERSAL_MAX_ORDER_SH":50,"H_MIN_ASK":0.05,"H_MAX_ASK":0.98,"H_CAP_HEADROOM":0.01,"H_MIN_DEPTH_SH":4,"H_BASE_ORDER_SH":7,"H_MIN_ORDER_SH":4,"H_COOLDOWN_MS":2000,"MAX_SESSION_LOSS":25,"LATENCY_MS":520}',
      TRACKER_DISABLED: "1",
      SHOW_TRACKER: "0",
      MANUAL_BUY_MODE: "0",
      ASSET: "btc",
      INTERVAL: "5m",
      TRACK_WALLET: "0x75cc3b63a2f2423085e10706c78b494017b93ce1",
      UI_PORT: "4520",
      UI_SAMPLE_MS: "120",
      DATA_DIR: "./data/fastmx-live",
      LOG_DIR: "./logs/fastmx-live",
      RUNTIME_CONFIG_FILE: "./data/fastmx-live/runtime-config.json",
      MONGO_DB: "poly_fastmx",
      RECORD_LIVE_TICKS: "1",
      VERBOSE_LOG: "1",
    },
  }],
};
