// Isolated FastMX live-shadow process. The app is hard-locked to simulation in config.js as well as here.
module.exports = {
  apps: [{
    name: "poly-fastmx-simulation",
    script: "src/index.js",
    cwd: __dirname,
    exec_mode: "fork",
    instances: 1,
    autorestart: true,
    max_restarts: 50,
    restart_delay: 3000,
    max_memory_restart: "600M",
    time: true,
    merge_logs: true,
    out_file: "./data/fastmx-live/pm2-out.log",
    error_file: "./data/fastmx-live/pm2-err.log",
    env: {
      INSTANCE_NAME: "fastmx-live-simulation",
      MODE: "ui",
      AUTO_START: "1",
      EXECUTION_MODE: "simulation",
      SHADOW: "1",
      SHADOW_PARAMS_JSON: '{"STRATEGY":"wallet3048","W3048_SPEC_VERSION":3,"MAX_SESSION_LOSS":25,"LATENCY_MS":520}',
      TRACKER_DISABLED: "1",
      SHOW_TRACKER: "0",
      MANUAL_BUY_MODE: "0",
      ASSET: "btc",
      INTERVAL: "5m",
      TRACK_WALLET: "0x3048d65321be3497164cdfc2996f94f98a2e7537",
      UI_PORT: "4520",
      UI_SAMPLE_MS: "120",
      DATA_DIR: "./data/fastmx-live",
      LOG_DIR: "./logs/fastmx-live",
      RUNTIME_CONFIG_FILE: "./data/fastmx-live/runtime-config.json",
      MONGO_DB: "poly_fastmx",
      RECORD_LIVE_TICKS: "1",
      VERBOSE_LOG: "1",
    },
  }],
};
