// Isolated FastMX live-shadow process. The app is hard-locked to simulation in config.js as well as here.
module.exports = {
  apps: [{
    name: "poly-fastmx-simulation",
    script: "src/index.js",
    cwd: __dirname,
    exec_mode: "fork",
    instances: 1,
    autorestart: true,
    max_restarts: 50,
    restart_delay: 3000,
    max_memory_restart: "600M",
    time: true,
    merge_logs: true,
    out_file: "./data/fastmx-live/pm2-out.log",
    error_file: "./data/fastmx-live/pm2-err.log",
    env: {
      INSTANCE_NAME: "fastmx-live-simulation",
      MODE: "ui",
      AUTO_START: "1",
      EXECUTION_MODE: "simulation",
      SHADOW: "1",
      SHADOW_PARAMS_JSON: JSON.stringify({
        STRATEGY: "helpme", SIZE: 7, LIMIT: 0.98, LATENCY_MS: 520,
        H_SESSION_POLICY_ON: true,
        H_HEDGE_ON: false,
        H_REVERSAL_DYNAMIC_SIZE_ON: true,
        H_REVERSAL_RISK_USD: 2,
        H_REVERSAL_ECONOMIC_GATE_ON: false,
        H_DYNAMIC_SIZE_ON: true,
        H_ENTRY_RISK_USD: 2,
        H_RISK_LIMITS_ON: true,
        H_MAX_ORDER_SH: 100,
        H_MAX_GROSS_SH: 500,
        H_MAX_ROUND_COST_USD: 250,
        H_MAX_ROUND_WORST_LOSS_USD: 10,
        H_MAX_SIGNAL_ORDERS: 4,
        H_PARTICIPATION_ON: true,
        H_PARTICIPATION_START_S: 90,
        H_PARTICIPATION_END_S: 299,
        H_PARTICIPATION_RETRY_MS: 1000,
        H_PARTICIPATION_RISK_USD: 1,
        H_PARTICIPATION_MAX_ASK: 0.99,
        H_RESCUE_MAKER_ON: true,
        H_RESCUE_START_S: 270,
        H_RESCUE_END_S: 299,
        H_RESCUE_PRICE_HIGH: 0.02,
        H_RESCUE_PRICE_LOW: 0.01,
        H_RESCUE_TOTAL_RISK_USD: 2,
        H_RESCUE_RETAIN_SH: 25,
        H_RESCUE_REQUIRE_BOTH: true,
        H_RESCUE_MAKER_LATENCY_MS: 130,
        H_RESCUE_SIM_FILL_PCT: 100,
        H_RESCUE_SIM_TOUCH_MS: 250,
        H_LIVE_ORDER_TYPE: "FAK",
        MAX_SESSION_LOSS: 25,
      }),
      TRACKER_DISABLED: "1",
      SHOW_TRACKER: "0",
      MANUAL_BUY_MODE: "0",
      ASSET: "btc",
      INTERVAL: "5m",
      TRACK_WALLET: "0x75cc3b63a2f2423085e10706c78b494017b93ce1",
      UI_PORT: "4520",
      UI_SAMPLE_MS: "120",
      DATA_DIR: "./data/fastmx-live",
      LOG_DIR: "./logs/fastmx-live",
      RUNTIME_CONFIG_FILE: "./data/fastmx-live/runtime-config.json",
      MONGO_DB: "poly_fastmx",
      RECORD_LIVE_TICKS: "1",
      VERBOSE_LOG: "1",
    },
  }],
};
